Resources:
  AuthorizerJWTApiGateway:
    Type: AWS::ApiGateway::Authorizer
    DependsOn:
      - ApiGatewayRestApi
    Properties:
      Name: LambdaAuthorizer
      Type: TOKEN
      IdentitySource: method.request.header.Authorization
      RestApiId: !Ref ApiGatewayRestApi
      AuthorizerUri:
        Fn::Join:
          - ""
          - - "arn:aws:apigateway:"
            - Ref: AWS::Region
            - ":lambda:path/2015-03-31/functions/"
            - "arn:aws:lambda:ap-northeast-2:503561434552:function:lambda-authorizer-service-prod-AuthorizerJWT"
            - "/invocations"

  LambdaInvokePermissionForApiGateway:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: "arn:aws:lambda:ap-northeast-2:503561434552:function:lambda-authorizer-service-prod-AuthorizerJWT"
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: ApiGatewayRestApi
            - "/*"
