Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: ECS-Cluster-ahim
  InstitutionTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: institution-TD-ahim
      NetworkMode: awsvpc
      Cpu: "256"
      Memory: "512"
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: ExecutionRole.Arn
      TaskRoleArn: TaskRole.Arn
      ContainerDefinitions:
        - Name: institution-service-container-ahim
          Image: 503561434552.dkr.ecr.ap-northeast-2.amazonaws.com/institution-service:latest
          PortMappings:
            - ContainerPort: 8080
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/LG-task
              awslogs-region: ap-northeast-2
              awslogs-stream-prefix: ecs
  StudentTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: student-TD-ahim
      NetworkMode: awsvpc
      Cpu: "256"
      Memory: "512"
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: ExecutionRole.Arn
      TaskRoleArn: TaskRole.Arn
      ContainerDefinitions:
        - Name: student-service-container-ahim
          Image: 503561434552.dkr.ecr.ap-northeast-2.amazonaws.com/student-service:latest
          PortMappings:
            - ContainerPort: 8080
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/LG-task
              awslogs-region: ap-northeast-2
              awslogs-stream-prefix: ecs
  CompanyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: company-TD-ahim
      NetworkMode: awsvpc
      Cpu: "256"
      Memory: "512"
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: ExecutionRole.Arn
      TaskRoleArn: TaskRole.Arn
      ContainerDefinitions:
        - Name: company-service-container-ahim
          Image: 503561434552.dkr.ecr.ap-northeast-2.amazonaws.com/company-service:latest
          PortMappings:
            - ContainerPort: 8080
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/LG-task
              awslogs-region: ap-northeast-2
              awslogs-stream-prefix: ecs
  StudentECSService:
    Type: AWS::ECS::Service
    DependsOn:
      - StudentTargetGroup
      - MyALBListener
      - StudentPathRule
    Properties:
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref StudentTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !Ref PublicSubnet1
            - !Ref PublicSubnet2
          SecurityGroups:
            - !Ref MyECSSecurityGroup
          AssignPublicIp: ENABLED
      LoadBalancers:
        - TargetGroupArn: !Ref StudentTargetGroup
          ContainerName: student-service-container-ahim
          ContainerPort: 8080
  InstitutionECSService:
    Type: AWS::ECS::Service
    DependsOn:
      - InstitutionTargetGroup
      - MyALBListener
      - InstitutionPathRule
    Properties:
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref InstitutionTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !Ref PublicSubnet1
            - !Ref PublicSubnet2
          SecurityGroups:
            - !Ref MyECSSecurityGroup
          AssignPublicIp: ENABLED
      LoadBalancers:
        - TargetGroupArn: !Ref InstitutionTargetGroup
          ContainerName: institution-service-container-ahim
          ContainerPort: 8080
  CompanyECSService:
    Type: AWS::ECS::Service
    DependsOn:
      - CompanyTargetGroup
      - MyALBListener
      - CompanyPathRule
    Properties:
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref CompanyTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !Ref PublicSubnet1
            - !Ref PublicSubnet2
          SecurityGroups:
            - !Ref MyECSSecurityGroup
          AssignPublicIp: ENABLED
      LoadBalancers:
        - TargetGroupArn: !Ref CompanyTargetGroup
          ContainerName: company-service-container-ahim
          ContainerPort: 8080
