Resources:
  # ECS 클러스터 생성
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: KHJKDW-ECS-Cluster
  # ECS 태스크 정의 (컨테이너 3개 각각의 태스크로 분리)
  InstitutionTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: institution-task-family-KHJKDW
      NetworkMode: awsvpc
      Cpu: "256"
      Memory: "512"
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: institution-service-container-KHJKDW
          Image: 503561434552.dkr.ecr.ap-northeast-2.amazonaws.com/institution-service:latest
          PortMappings:
            - ContainerPort: 8080
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/KHJKDW-task
              awslogs-region: ap-northeast-2
              awslogs-stream-prefix: ecs

  StudentTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: student-task-family-KHJKDW
      NetworkMode: awsvpc
      Cpu: "256"
      Memory: "512"
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: student-service-container-KHJKDW
          Image: 503561434552.dkr.ecr.ap-northeast-2.amazonaws.com/student-service:latest
          PortMappings:
            - ContainerPort: 8080
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/KHJKDW-task
              awslogs-region: ap-northeast-2
              awslogs-stream-prefix: ecs

  CompanyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: company-task-family-KHJKDW
      NetworkMode: awsvpc
      Cpu: "256"
      Memory: "512"
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: company-service-container-KHJKDW
          Image: 503561434552.dkr.ecr.ap-northeast-2.amazonaws.com/company-service:latest
          PortMappings:
            - ContainerPort: 8080
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/KHJKDW-task
              awslogs-region: ap-northeast-2
              awslogs-stream-prefix: ecs

  # ECS 서비스 정의 (컨테이너 3개 각각의 서비스로 분리)
  StudentECSService:
    Type: AWS::ECS::Service
    DependsOn:
      - StudentTargetGroup
      - MyALBListener
      - StudentPathRule
    Properties:
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref StudentTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !Ref PublicSubnet1
            - !Ref PublicSubnet2
          SecurityGroups:
            - !Ref MyECSSecurityGroup
          AssignPublicIp: ENABLED
      LoadBalancers:
        - TargetGroupArn: !Ref StudentTargetGroup
          ContainerName: student-service-container-KHJKDW
          ContainerPort: 8080

  InstitutionECSService:
    Type: AWS::ECS::Service
    DependsOn:
      - InstitutionTargetGroup
      - MyALBListener
      - InstitutionPathRule
    Properties:
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref InstitutionTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !Ref PublicSubnet1
            - !Ref PublicSubnet2
          SecurityGroups:
            - !Ref MyECSSecurityGroup
          AssignPublicIp: ENABLED
      LoadBalancers:
        - TargetGroupArn: !Ref InstitutionTargetGroup
          ContainerName: institution-service-container-KHJKDW
          ContainerPort: 8080

  CompanyECSService:
    Type: AWS::ECS::Service
    DependsOn:
      - CompanyTargetGroup
      - MyALBListener
      - CompanyPathRule
    Properties:
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref CompanyTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !Ref PublicSubnet1
            - !Ref PublicSubnet2
          SecurityGroups:
            - !Ref MyECSSecurityGroup
          AssignPublicIp: ENABLED
      LoadBalancers:
        - TargetGroupArn: !Ref CompanyTargetGroup
          ContainerName: company-service-container-KHJKDW
          ContainerPort: 8080