service: quiz-api

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  environment:
    DYNAMODB_TABLE: ${self:service}
    REGION: ${aws:region}
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}/index/*"
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

functions:
  createPost:
    handler: quiz.createQuiz
    events:
      - httpApi:
          path: /v1/create
          method: POST

  getPost:
    handler: quiz.getQuiz
    events:
      - httpApi:
          path: /v1/{id}
          method: GET

  listPostsByCourse: # 코스 ID로 퀴즈 목록 조회
    handler: quiz.listQuizByCourse
    events:
      - httpApi:
          path: /v1/course/{courseId}/quizzes
          method: GET

  updatePost:
    handler: quiz.updateQuiz
    events:
      - httpApi:
          path: /v1/{id}
          method: PUT

  deletePost:
    handler: quiz.deleteQuiz
    events:
      - httpApi:
          path: /v1/{id}
          method: DELETE

  answerQuiz:
    handler: quiz.answerQuiz
    events:
      - httpApi:
          path: /v1/answer
          method: POST

resources:
  Resources:
    QuizTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

package:
  patterns:
    - "!node_modules/.bin/**"
    - "node_modules/**"
    - "quiz.mjs"
  individually: false

custom:
  esbuild:
    bundle: true
    minify: false
    format: esm
    sourcemap: true
    target: node20
    platform: node
    outExtension:
      ".js": ".mjs"
    mainFields:
      - module
      - main
