service: exam-api

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  environment:
    DYNAMODB_TABLE: ${self:service}
    REGION: ${aws:region}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}/index/courseId-index"
        - Effect: Allow
          Action:
            - logs:PutLogEvents

            - logs:CreateLogGroup
            - logs:CreateLogStream
          Resource: "*"
functions:
  createExam:
    handler: src/create-exam.handler
    events:
      - http:
          path: /v1/exam/{courseId}/create
          method: POST
          cors: true
    package:
      include:
        - src/create-exam.js
        - node_modules/aws-sdk/**
      exclude:
        - src/**
        - node_modules/**

  getExam:
    handler: src/get-exam.handler
    events:
      - http:
          path: /v1/exam/{courseId}/get
          method: GET
          cors: true
    package:
      include:
        - src/get-exam.js
        - node_modules/aws-sdk/**
      exclude:
        - src/**
        - node_modules/**

  submitExam:
    handler: src/submit-exam.handler
    events:
      - http:
          path: /v1/exam/submit
          method: POST
          cors: true
    package:
      include:
        - src/get-exam.js
        - node_modules/aws-sdk/**
      exclude:
        - src/**
        - node_modules/**

resources:
  Resources:
    ExamTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: courseId
            AttributeType: S
        KeySchema:
          - AttributeName: courseId
            KeyType: HASH

    ExamSubmitTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: exam-submit-api
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: examId
            AttributeType: S
        KeySchema:
          - AttributeName: examId
            KeyType: HASH

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.ahimmoyak.click
    basePath: "exam"
    stage: dev
    createRoute53Record: true
    endpointType: REGIONAL
    certificateName: "arn:aws:acm:ap-northeast-2:503561434552:certificate/c56e0793-3d74-4357-9d42-bebb8e34511c"

package:
  patterns:
    - "!./**"
    - "src/**"
    - "package.json"
    - "node_modules/**"
