service: exam-api

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  environment:
    DYNAMODB_TABLE: ${self:service}-exam-table # 명확한 테이블 이름으로 변경
    PROVIDE_TABLE: ${self:service}-provide-table # 제공 테이블 이름
    REGION: ${aws:region}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.PROVIDE_TABLE}"
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.PROVIDE_TABLE}/index/*" # GSI에 대한 권한 추가
        - Effect: Allow
          Action:
            - logs:PutLogEvents
            - logs:CreateLogGroup
            - logs:CreateLogStream
          Resource: "*"

functions:
  getExamList:
    handler: src/get-exam-list.handler
    events:
      - http:
          path: /v1/{courseId}/get
          method: GET
          cors: true
    package:
      include:
        - src/get-exam-list.js
        - node_modules/aws-sdk/**
      exclude:
        - src/**
        - node_modules/**

  getProvideExamList:
    handler: src/get-provide-exam-list.handler
    events:
      - http:
          path: /v1/provide/{provideId}
          method: GET
          cors: true
    package:
      include:
        - src/get-provide-exam-list.js
        - node_modules/aws-sdk/**
      exclude:
        - src/**
        - node_modules/**

  createExam:
    handler: src/create-exam.handler
    events:
      - http:
          path: /v1/{courseId}/create
          method: POST
          cors: true
    package:
      include:
        - src/create-exam.js
        - node_modules/aws-sdk/**
      exclude:
        - src/**
        - node_modules/**

resources:
  Resources:
    ExamTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: courseId
            AttributeType: S
          - AttributeName: examId
            AttributeType: S
        KeySchema:
          - AttributeName: courseId
            KeyType: HASH
          - AttributeName: examId
            KeyType: RANGE

    ProvideTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.PROVIDE_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: provideId
            AttributeType: S
          - AttributeName: courseId
            AttributeType: S
        KeySchema:
          - AttributeName: provideId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: NewProvideIndex # 새 GSI 이름
            KeySchema:
              - AttributeName: courseId
                KeyType: HASH
            Projection:
              ProjectionType: ALL

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.ahimmoyak.click
    basePath: "exam"
    stage: dev
    createRoute53Record: true
    endpointType: REGIONAL
    certificateName: "arn:aws:acm:ap-northeast-2:503561434552:certificate/c56e0793-3d74-4357-9d42-bebb8e34511c"

package:
  patterns:
    - "!./**"
    - "src/**"
    - "package.json"
    - "node_modules/**"
