service: exam-api

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  environment:
    DYNAMODB_TABLE: ${self:service}
    EXAM_SUBMIT_TABLE: exam-submit-api
    REGION: ${aws:region}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.EXAM_SUBMIT_TABLE}"
        - Effect: Allow
          Action:
            - logs:PutLogEvents
            - logs:CreateLogGroup
            - logs:CreateLogStream
          Resource: "*"
functions:
  getExamList:
    handler: src/get-exam-list.handler
    events:
      - http:
          path: /v1/{courseId}/get
          method: GET
          cors: true
    package:
      include:
        - src/get-exam-list.js
        - node_modules/aws-sdk/**
      exclude:
        - src/**
        - node_modules/**

  createExam:
    handler: src/create-exam.handler
    events:
      - http:
          path: /v1/{courseId}/create
          method: POST
          cors: true
    package:
      include:
        - src/create-exam.js
        - node_modules/aws-sdk/**
      exclude:
        - src/**
        - node_modules/**

  manageExam:
    handler: src/manage-exam.handler
    events:
      - http:
          path: /v1/{courseId}/{examId}/edit
          method: PUT
          cors: true
    package:
      include:
        - src/manage-exam.js
        - node_modules/aws-sdk/**
      exclude:
        - src/**
        - node_modules/**

  deleteExam:
    handler: src/delete-exam.handler
    events:
      - http:
          path: /v1/{courseId}/{examId}/delete
          method: DELETE
          cors: true
    package:
      include:
        - src/delete-exam.js
        - node_modules/aws-sdk/**
      exclude:
        - src/**
        - node_modules/**

  deleteQuiz:
    handler: src/delete-quiz.handler
    events:
      - http:
          path: /v1/{courseId}/{examId}/{quizId}/delete
          method: DELETE
          cors: true
    package:
      include:
        - src/delete-quiz.js
        - node_modules/aws-sdk/**
      exclude:
        - src/**
        - node_modules/**

  checkExam:
    handler: src/check-exam.handler
    events:
      - http:
          path: /v1/{courseId}/{examId}/check
          method: GET
          cors: true
    package:
      include:
        - src/check-exam.js
        - node_modules/aws-sdk/**
      exclude:
        - src/**
        - node_modules/**

  submitExam:
    handler: src/submit-exam.handler
    events:
      - http:
          path: /v1/{courseId}/submit
          method: POST
          cors: true
    package:
      include:
        - src/get-exam-list.js
        - node_modules/aws-sdk/**
      exclude:
        - src/**
        - node_modules/**

resources:
  Resources:
    ExamTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: courseId
            AttributeType: S
          - AttributeName: examId
            AttributeType: S
        KeySchema:
          - AttributeName: courseId
            KeyType: HASH
          - AttributeName: examId
            KeyType: RANGE

    ExamSubmitTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.EXAM_SUBMIT_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: examId
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: examId
            KeyType: HASH
          - AttributeName: username
            KeyType: RANGE

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.ahimmoyak.click
    basePath: "exam"
    stage: dev
    createRoute53Record: true
    endpointType: REGIONAL
    certificateName: "arn:aws:acm:ap-northeast-2:503561434552:certificate/c56e0793-3d74-4357-9d42-bebb8e34511c"

package:
  patterns:
    - "!./**"
    - "src/**"
    - "package.json"
    - "node_modules/**"
