name: company-service deploy

on:
  pull_request:
    branches:
      - microservice
    types:
      - closed
    paths:
      - 'company-service/**'
jobs:
  deploy:
    if: ${{github.event.pull_request.merged}}
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK17 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Create necessary directories
        run: mkdir -p ./company-service/src/main/resources

      - name: application.yml 파일 만들기
        run: |
          echo -e "${{ secrets.COMPANY_APPLICATION_PROPERTIES }}" > ./company-service/src/main/resources/application.yml

      - name: 테스트 및 빌드하기
        working-directory: ./company-service
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: AWS Resource 에 접근할 수 있게 AWS credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: ECR에 로그인 하기.
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: ECR에 로그인 한 결과 확인
        run: echo ${{ steps.login-ecr.outputs.registry }}

      - name: Docker 이미지 생성
        working-directory: ./company-service
        run: docker build -t company-cicd .

      - name: Dokcer 이미지 생성 확인
        run: |
          ls
          pwd

      - name: Docker 이미지에 Tag 붙이기
        run: docker tag company-cicd ${{ steps.login-ecr.outputs.registry }}/company-service:latest

      - name: ECR에 docker image push 하기
        run: docker push ${{ steps.login-ecr.outputs.registry }}/company-service:latest

      - name: 태스크 정의 업데이트
        id: task-def
        run: |
          # 1. 기존 태스크 정의 가져오기
          TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition ${{ secrets.ECS_TASK_DEFINITION_NAME }} --query 'taskDefinition')
          
          # 2. 새 이미지 URI로 컨테이너 정의 업데이트
          NEW_CONTAINER_DEFINITION=$(echo $TASK_DEFINITION | jq --arg IMAGE_URI "${{ steps.login-ecr.outputs.registry }}/company-service:latest" '.containerDefinitions[0].image=$IMAGE_URI')
          
          # 3. 불필요한 정보 제거
          NEW_TASK_DEFINITION=$(echo $TASK_DEFINITION | jq '.taskDefinitionArn=null | .revision=null | .status=null | .requiresAttributes=null | .compatibilities=null | .registeredAt=null | .registeredBy=null')
          
          # 4. 새 컨테이너 정의를 태스크 정의에 포함
          FINAL_TASK_DEFINITION=$(echo $NEW_TASK_DEFINITION | jq --argjson containerDef "$NEW_CONTAINER_DEFINITION" '.containerDefinitions=$containerDef')
          
          # 5. 새로운 태스크 정의를 JSON 파일로 저장하고 등록
          echo $FINAL_TASK_DEFINITION > new-task-def.json
          aws ecs register-task-definition --cli-input-json file://new-task-def.json

      - name: ECS 서비스 업데이트 및 배포 강제
        run: |
          aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER_NAME }} \
            --service ${{ secrets.COMPANY_ECS_SERVICE_NAME }} \
            --force-new-deployment