name: institution-service deploy

on:
  pull_request:
    branches:
      - microservice
    paths:
      - 'institution-service/**'


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK17 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.yml 파일 만들기
        run: echo "${{ secrets.INSTITUTION_APPLICATION_PROPERTIES }}" > ./institution-service/src/main/resources/application.yml

      - name: 테스트 및 빌드하기
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Test
        run: |
          ls
          pwd

      - name: AWS Resource 에 접근할 수 있게 AWS credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: ECR에 로그인 하기.
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # ECR에 성공적으로 로그인이 되면, 반환되는 값을 docker image 파일명으로 사용하기 위해
      # 반환된 값이 있는지 확인하기 위해 출력
      - name: ECR에 로그인 한 결과 확인
        run: echo ${{ steps.login-ecr.outputs.registry }}

      # Dockerfile  을 참조해서 docker image 생성
      - name: Docker 이미지 생성
        run: docker build -t institution-cicd .

      - name: Dokcer 이미지 생성 확인
        run: |
          ls
          pwd
      # ECR 의 URI 를 이요해서 docker image tag를 만듬

      - name: Docker 이미지에 Tag 붙이기
        run: docker tag cicd-server ${{ steps.login-ecr.outputs.registry }}/institution-cicd:latest

      - name: ECR에 docker image push 하기
        run: docker push ${{ steps.login-ecr.outputs.registry }}/institution-cicd:latest
